import * as T from 'three';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';import {createBodyRig} from '../src/bodyRig';import {attachAnatomyAsset} from '../src/anatomyAsset';import {exercises} from '../src/domain';import {applyExercisePose,muscleAppearance} from '../src/movement';
const asset=await new GLTFLoader().loadAsync('/models/anatomy-v4.glb?v=face-contour-2');const rig=createBodyRig();attachAnatomyAsset(rig,asset.scene);const scene=new T.Scene();scene.add(rig.root);scene.add(new T.HemisphereLight('#fffef6','#7b826f',1.6));const light=new T.DirectionalLight('#ffffff',2.7);light.position.set(-3,6,5);scene.add(light);const renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setSize(850,680);renderer.setClearColor('#f3f4ed');renderer.toneMapping=T.ACESFilmicToneMapping;renderer.outputColorSpace=T.SRGBColorSpace;const plane=new T.Mesh(new T.PlaneGeometry(10,10),new T.MeshStandardMaterial({color:'#e0e5d8',roughness:1}));plane.rotation.x=-Math.PI/2;plane.position.y=-.015;scene.add(plane);
const params=new URLSearchParams(location.search);const page=Number(params.get('part')??0);const ids=(params.get('ids')??'press,Cable_Rope_Overhead_Triceps_Extension,Incline_Push-Up,Front_Barbell_Squat,Barbell_Squat,Dumbbell_Flyes').split(',');const selected=exercises.filter(e=>ids.includes(e.id));
const stats:any[]=[];
for(const e of selected)for(const a of [0,.5,1]){
 applyExercisePose(rig,e,a);rig.root.updateMatrixWorld(true);rig.skeleton.update();rig.mats.forEach(({mat,id})=>mat.color.set(muscleAppearance(id,e.primary,e.secondary,false,0).color));
 const camera=new T.PerspectiveCamera(36,850/680,.1,100);const low=['bench','floor'].includes(e.animation?.framing??'') || ['pushup','bridge'].includes(e.id);camera.position.set(4.8,low?3.0:3.4,4.3);camera.lookAt(0,low?1.0:2.7,.15);renderer.render(scene,camera);
 const fig=document.createElement('figure');fig.innerHTML=`<figcaption>${e.name} · ${a===0?'起始':a===1?'终点':'途中'}</figcaption>`;const img=document.createElement('img');img.src=renderer.domElement.toDataURL();fig.append(img);document.querySelector('main')!.append(fig);
 const pts=rig.arms.map(a=>({wrist:a.hand.getWorldPosition(new T.Vector3()).toArray(),grip:a.grip.getWorldPosition(new T.Vector3()).toArray()}));stats.push({id:e.id,a,arms:pts});
}
renderer.dispose();renderer.forceContextLoss();(document as any).reviewStats=stats;document.body.dataset.ready='true';
